name: Docker Image CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: endpointtest/yamllint
      DOCKER_FILE: Dockerfile
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker logout
          docker login -u ${{ secrets.DOCKERHUB_U }} -p ${{ secrets.DOCKERHUB_T }}
          docker build . --file $DOCKER_FILE -t $DOCKER_IMAGE:$GITHUB_SHA -t $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:$GITHUB_SHA
          docker push $DOCKER_IMAGE:latest
